---
version: '3.7'
services:

  sidekiq: &yolact_base
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: yolact-minimal:gpu-latest
    working_dir: /yolact
    volumes:
    - ./server:/yolact/server
    - yolact-models:/yolact/weights
    - yolact-results:/yolact/results
    command: ./scripts/download_data.sh

  yolact:
    <<: *yolact_base
    ports:
    - "8000:8000"
    restart: unless-stopped
    command: ["/bin/bash"]
    networks:
    - internal
    - web # for tests purpose    

networks:
  internal:
  web:
    external: true

volumes:
  yolact-models:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/weights
  yolact-results:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/results
